title: "Long-Term Perception for Autonomy in Dynamic Human-shared Environments: What Do Robots Need?"
description: Title
sitename: Longterm-Perception-WS/2024
baseurl: "/Longterm-Perception-WS/2024"
url: "https://mit-spark.github.io"
