title: "Long-Term Perception for Autonomy in Dynamic Human-shared Environments: What Do Robots Need?"
description: Title
sitename: Longterm-Perception@IROS2024
baseurl: "/Longterm-Perception-WS"
url: "https://mit-spark.github.io"

# Scholar
# ========================================================================================
scholar:
  style: apa
  locale: en
  sort_by: year, month
  order: descending
  source: ./
  bibliography: resources.bib
  bibliography_template: bib
  replace_strings: true
  join_strings: false
  query: "@*"

plugins:
  - jekyll/scholar

sass:
  sass_dir: /assets/_sass
  style: :compressed
collections:
  - features
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.txt
  - CNAME
  - Makefile
  - resources.bib
