#title: "Long-Term Perception for Autonomy in Dynamic Human-shared Environments: What Do Robots Need?"
#description: "Informaton about our workshop on 'Long-Term Perception for Autonomy in Dynamic Human-shared Environments: What Do Robots Need?'"
#sitename: Longterm-Perception-WS/2024
#baseurl: "/Longterm-Perception-WS/2024"
#url: "https://mit-spark.github.io"
theme: minima #jekyll-theme-minimal
